// Frontend/System Design/angular/src/app/components/welcome-screen/welcome-screen.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-welcome-screen',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './welcome-screen.component.html',
  styleUrls: ['./welcome-screen.component.css']
})
export class WelcomeScreenComponent {
  @Output() selectComponent = new EventEmitter<string>();

  cards = [
    {
      key: 'carousel',
      title: 'Image Carousel',
      desc: 'An interactive, responsive image slider featuring automatic rotation, custom interval controls, transitions, and dot indicators.'
    },
    {
      key: 'autocomplete',
      title: 'Autocomplete Search',
      desc: 'A search-as-you-type autocomplete input component featuring matched text highlighting, dropdown suggestions, and keyboard arrow key navigation.'
    }
  ];

  onSelect(key: string) {
    this.selectComponent.emit(key);
  }
}

<div class="welcome-container">
  <div class="welcome-header">
    <h1 class="welcome-title">System Design Sandbox</h1>
    <p class="welcome-subtitle">
      Welcome to the Angular Machine Coding practice sandbox. Select a component from the sidebar or click one of the modules below to start exploring the implementation.
    </p>
  </div>

  <div class="welcome-grid">
    <div *ngFor="let card of cards" class="welcome-card">
      <h3 class="card-title">{{card.title}}</h3>
      <p class="card-desc">{{card.desc}}</p>
      <button type="button" (click)="onSelect(card.key)" class="card-action-btn">Launch Demo &rarr;</button>
    </div>
  </div>
  
  <div class="welcome-footer">
    <p>Interactive playground designed to master UI components and machine coding interviews.</p>
  </div>
</div>

// Frontend/System Design/react/src/components/WelcomeScreen.jsx
import React from "react";

export default function WelcomeScreen({ onSelectComponent }) {
  const cards = [
    {
      key: "carousel",
      title: "Image Carousel",
      desc: "An interactive, responsive image slider featuring automatic rotation, custom interval controls, transitions, and dot indicators.",
      color: "linear-gradient(135deg, #FF6B6B 0%, #FF8E53 100%)",
    },
    {
      key: "autocomplete",
      title: "Autocomplete Search",
      desc: "A search-as-you-type autocomplete input component featuring matched text highlighting, dropdown suggestions, and keyboard arrow key navigation.",
      color: "linear-gradient(135deg, #4E4376 0%, #2B5876 100%)",
    }
  ];

  return (
    <div className="welcome-container">
      <div className="welcome-header">
        <h1 className="welcome-title">System Design Sandbox</h1>
        <p className="welcome-subtitle">
          Welcome to the React Machine Coding practice sandbox. Select a component from the sidebar or click one of the modules below to start exploring the implementation.
        </p>
      </div>

      <div className="welcome-grid">
        {cards.map((card) => (
          <div
            key={card.key}
            className="welcome-card"
            style={{ "--hover-color": card.color }}
            
          >
            <h3 className="card-title">{card.title}</h3>
            <p className="card-desc">{card.desc}</p>
            <button type="button" onClick={() => onSelectComponent(card.key)} className="card-action-btn">Launch Demo &rarr;</button>
          </div>
        ))}
      </div>
      
      <div className="welcome-footer">
        <p>Interactive playground designed to master UI components and machine coding interviews.</p>
      </div>
    </div>
  );
}
