// Frontend/System Design/react/src/components/Sidebar.jsx
import React from "react";

export default function Sidebar({ activeComponent, onSelectComponent }) {
  const menuItems = [
    { key: "welcome", label: "Dashboard Home" },
    { key: "carousel", label: "Image Carousel" },
    { key: "autocomplete", label: "Autocomplete Search" },
    { key: "otpInput", label: "OTP Input" }
  ];

  return (
    <aside className="app-sidebar">
      <div className="sidebar-brand" onClick={() => onSelectComponent("welcome")}>
        <div className="brand-text">
          <h2>React Sandbox</h2>
          <span>Machine Coding</span>
        </div>
      </div>

      <nav className="sidebar-nav">
        <ul className="nav-list">
          {menuItems.map((item) => {
            const isActive = activeComponent === item.key;
            return (
              <li key={item.key} className="nav-item">
                <button
                  type="button"
                  className={`nav-link ${isActive ? "active" : ""}`}
                  onClick={() => onSelectComponent(item.key)}
                >
                  <span className="nav-label">{item.label}</span>
                  {isActive && <span className="active-indicator" />}
                </button>
              </li>
            );
          })}
        </ul>
      </nav>
    </aside>
  );
}

// Frontend/System Design/angular/src/app/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent {
  @Input() activeComponent: string = 'welcome';
  @Output() selectComponent = new EventEmitter<string>();

  menuItems = [
    { key: 'welcome', label: 'Dashboard Home' },
    { key: 'carousel', label: 'Image Carousel' },
    { key: 'autocomplete', label: 'Autocomplete Search' },
    { key: 'otp-input', label: 'OTP Input' }
  ];

  onSelect(key: string) {
    this.selectComponent.emit(key);
  }
}

<aside class="app-sidebar">
  <div class="sidebar-brand" (click)="onSelect('welcome')">
    <div class="brand-text">
      <h2>System Sandbox</h2>
      <span>Machine Coding</span>
    </div>
  </div>

  <nav class="sidebar-nav">
    <ul class="nav-list">
      <li *ngFor="let item of menuItems" class="nav-item">
        <button
          type="button"
          class="nav-link"
          [class.active]="activeComponent === item.key"
          (click)="onSelect(item.key)"
        >
          <span class="nav-label">{{item.label}}</span>
          <span *ngIf="activeComponent === item.key" class="active-indicator"></span>
        </button>
      </li>
    </ul>
  </nav>
</aside>
